CUDA_VISIBLE_DEVICES=0 python qwen_inference_ovu_proto.py
   --model_path Qwen/Qwen2-VL-7B-Instruct \
      --dataset mlvu   \
      --output_dir results/mlvu   \
      --exp_tag mlvu   \
      --max_frames_num 32   \
      --use_block_processing   \
      --block_size 4   \
      --compress_frame_num 3   \
      --compression_method prototrack-kv   \
      --per_frame   \
      --prototrack_proto_frames 2   \
      --prototrack_pq_subspaces 8   \
      --prototrack_pq_codebook_size 16   \
      --prototrack_pq_kmeans_iters 2   \
      --prototrack_pq_sample_size 512   